### ISSUE TITLE
SCT Puppet Pipeline Failed while deploying products with TagOption Enabled

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-puppet#613] opened 2022-12-07 13:43 UTC
Reopening -  Launches are not respecting tag options #611 - I have tested this by manually associating tagOptions to existing portfolio and redployed successfully using puppet options. Existing product was not updated with Tags from TagOptions. However, terminating and recreating product worked. 

**Next step is to create tag options in factory and deploy via puppet.** 

# Steps to reproduce

1. create a portfolio using factory that has tag options
2. set tag options sharing to true
3. provision a product in a spoke via a launch

# Expected results
1. provisioned product should have tags from tag options

# Actual results
1. Puppet Pipeline failed during deployment

# Error Logs : Portfolio & Product listed in error logs are available 
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/37020616/206194102-ea965f20-5bff-4b0d-8c32-8fd84bbe2b5f.png">

#

**Comment by eamonnfaherty** [comment] 2022-12-19 09:32
At the moment the only support for tag options is when you have created and applied them before provisioning.  Are you trying to do something else?

**Comment by shydhanya** [comment] 2022-12-20 17:41
Thanks Eamonn. Upgraded to latest version 0.213.  I have successfully launched (mandatory)products with TagOptions while provisioning for first time. 

However, spoke-local-portfolios (elective) products deployment has missing TagOptions in both spoke portfolios and products. 

spoke-local-portfolio with missing TagOptions - 
<img width="824" alt="image" src="https://user-images.githubusercontent.com/37020616/208730457-4f35215c-73e7-4468-b4ee-334ee2cb5b16.png">

manifest.yaml
<img width="434" alt="image" src="https://user-images.githubusercontent.com/37020616/208731020-474d3f50-6120-42d7-9704-52da060f2383.png">

**Note**: Imported tab has TagOption available in both products and portfolios.

**Comment by eamonnfaherty** [comment] 2022-12-22 09:11
this is a dupe of this https://github.com/awslabs/aws-service-catalog-puppet/issues/612

**Closed by eamonnfaherty** 2022-12-22 09:11 UTC
Labels: question
