### ISSUE TITLE
Error during the build with "all" region tag.

### ISSUE THREAD

**Issue by VictorRaim** [awslabs/aws-service-catalog-puppet#206] opened 2019-11-21 16:54 UTC
Hi,

During my tests to deploy the same portfolio on multiple regions in single spoke account. I stumble to the following error:

_botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://servicecatalog.a.amazonaws.com/"_ 

[manifest.yaml.txt](https://github.com/awslabs/aws-service-catalog-puppet/files/3875814/manifest.yaml.txt)
[codebuild.log](https://github.com/awslabs/aws-service-catalog-puppet/files/3875812/codebuild.log)

**Comment by eamonnfaherty** [comment] 2019-11-21 17:13
Hi @VictorRaim 

Thanks for raising this issue and sorry to hear you have hit this issue.

Could you please confirm which version of puppet you are using.

**Comment by VictorRaim** [comment] 2019-11-21 17:51
The version is 0.53 of both the puppet and the bootstrapped account (different one).

**Comment by eamonnfaherty** [comment] 2019-11-25 23:54
Hi @VictorRaim Sorry for the delay here.

I have released a new version - 0.56.0.  I have tested the use of 'all' for the regions with portfolio sharing and cannot reproduce your issue.  Would you mind retesting please.

**Comment by eamonnfaherty** [comment] 2019-11-25 23:55
I will close this but feel free to reopen should you still see the issue.

**Closed by eamonnfaherty** 2019-11-25 23:55 UTC
Labels: question
