### ISSUE TITLE
Updating parameter for already provisioned product doesn't trigger a product update

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#54] opened 2019-05-29 11:43 UTC
Changing the parameter on an already provisioned product doesn't trigger an update to the product.

It looks like Puppet only checks if the version or product artefact id has changed, whereas it should also check to see if any of the parameters have also changed to determine whether a product should be updated.

**Comment by eamonnfaherty** [comment] 2019-05-29 12:03
Hi @jordan-evans 

Thanks for reporting this.  This was by design but I will look into how this can be handled.

**Comment by jordan-evans** [comment] 2019-05-29 13:08
Thanks @eamonnfaherty 

The only way we can update a product otherwise is to either to:

- Release a new version of it, then use the version bump as the opportunity to change the parameter
- Terminate & re-provision the product (which is difficult at scale, and means we have downtime of products in cases where a parameter update would just do in-place updates).

Neither of which is particularly appealing ☹️

**Comment by eamonnfaherty** [comment] 2019-05-29 16:40
Fixed in aws-service-catalog-puppet 0.0.44

**Closed by eamonnfaherty** 2019-05-29 16:40 UTC
Labels: enhancement
