### ISSUE TITLE
Product deployment failure stops all other product deployments to that account

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#55] opened 2019-05-29 11:45 UTC
It looks like when a product is failed to be deployed into an account, all further products meant to be deployed to that account aren't triggered.

I think this might be due to the entire thread for the account exiting when the product deployment fails.

I think it would be better if the account deployment thread continued on to try deploying the other products meant to be deployed to the account.

**Comment by eamonnfaherty** [comment] 2019-05-29 12:29
Hi @jordan-evans 

This was by design as there could be an issue with the account bootstrapping and so future provisions could be broken.  This also affects products that are dependencies for others.

I have been working on an alternative deployment engine to replace the one under the hood of this tool.  It will allow retries and some other useful capabilities.  I have one last blocker to resolve before releasing it.  

I will have a look at this issue today or tomorrow.

**Comment by eamonnfaherty** [comment] 2019-05-29 16:49
fixed in 0.0.45

**Closed** 2019-05-29 16:53 UTC
Labels: enhancement
