### ISSUE TITLE
fixed in 0.184.0 - An error occurred (ValidationException) when calling the PutEvents operation: Total size of the entries in the request is over the limit.

### ISSUE THREAD

**Issue by vc00778402** [awslabs/aws-service-catalog-puppet#563] opened 2022-09-08 12:14 UTC
fixed in 0.184.0

_Originally posted by @eamonnfaherty in https://github.com/awslabs/aws-service-catalog-puppet/issues/537#issuecomment-1206401623_

**Comment by vc00778402** [comment] 2022-09-08 12:16
The issue still persists after upgrading to 0.184.0. Kindly assist.

![image](https://user-images.githubusercontent.com/109735599/189119316-8f1796df-1fb6-4f94-8d23-f79328b0c555.png)

**Comment by eamonnfaherty** [comment] 2022-09-13 17:33
dupe of https://github.com/awslabs/aws-service-catalog-puppet/issues/537

**Closed by eamonnfaherty** 2022-09-13 17:33 UTC
